#include "src/game/envfx_snow.h"

const GeoLayout citras_wing_head_CAP_WINGS_DEAD[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, -90, 0),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_Wing_Cap_Head_Dead_Switch_Option_C_W_Dead_Cap_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_Wing_Cap_Head_Dead_Switch_Option_C_W_Dead_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt1_jump_citras_wing_head_CAP_WINGS_DEAD[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, -90, 0),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_Wing_Cap_Head_Dead_Switch_Option_C_W_Dead_Cap_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_Wing_Cap_Head_Dead_Switch_Option_C_W_Dead_Wings_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Half_Closed_Eyes__SKIN__1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Closed_Eyes__SKIN__2),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Closed_Eyes__SKIN__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Left_Eyes__SKIN__3),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Left_Eyes__SKIN__3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Right_Eyes__SKIN__4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Right_Eyes__SKIN__4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Up_Eyes__SKIN__5),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Up_Eyes__SKIN__5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Down_Eyes__SKIN__6),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Down_Eyes__SKIN__6),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Cap_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Wings_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt1),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt2),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt3),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt4),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt5),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt1_Eye_State_Switch_For_Wing_Cap_Head_opt6),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt1_jump_citras_wing_head_CAP_WINGS_DEAD),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt2_jump_citras_wing_head_CAP_WINGS_DEAD[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, -90, 0),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_Wing_Cap_Head_Dead_Switch_Option_C_W_Dead_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_Wing_Cap_Head_Dead_Switch_Option_C_W_Dead_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt2_jump_citras_wing_head_CAP_WINGS_DEAD),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt3_jump_citras_wing_head_CAP_WINGS_DEAD[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, -90, 0),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_Wing_Cap_Head_Dead_Switch_Option_C_W_Dead_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_Wing_Cap_Head_Dead_Switch_Option_C_W_Dead_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt3_jump_citras_wing_head_CAP_WINGS_DEAD),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Half_Closed_Eyes__SKIN__1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Half_Closed_Eyes__SKIN__1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Closed_Eyes__SKIN__2),
			GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Closed_Eyes__SKIN__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Left_Eyes__SKIN__3),
			GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Left_Eyes__SKIN__3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Right_Eyes__SKIN__4),
			GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Right_Eyes__SKIN__4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Up_Eyes__SKIN__5),
			GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Up_Eyes__SKIN__5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_C_W_Cap_mesh_layer_1_mat_override_Down_Eyes__SKIN__6),
			GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_C_W_Wings_mesh_layer_4_mat_override_Down_Eyes__SKIN__6),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout citras_wing_head_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mario_set_player_colors),
				GEO_ASM(8, geo_mario_set_player_colors),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_C_W_Cap_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_C_W_Wings_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt1),
							GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt2),
							GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt3),
							GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt4),
							GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt5),
							GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt0_Eye_State_Switch_For_Wing_Cap_Head_opt6),
							GEO_BRANCH(1, citras_wing_head_CAP_WINGS_DEAD),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt1),
					GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt2),
					GEO_BRANCH(1, citras_wing_head_Cap_Wings_Switch_opt3),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, citras_wing_head_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, citras_wing_head_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, citras_wing_head_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
